'use strict';
var BRL=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
var STORAGE_REGISTROS='controleUber99',STORAGE_TIMER='timerUber99',STORAGE_META='metaSemanalUber99',STORAGE_CUSTOS='custosVeiculoUber99';
var SUPABASE_URL='https://zmfferpuscowzogxiktd.supabase.co',SUPABASE_KEY='sb_publishable_wopq-H6SL-7-hK6M0kVFMA_vYeoYWeg',SUPABASE_TABLE='app_state';
var db=null,dbOnline=false,registros=[],timer={rodando:false,inicio:null,acumulado:0},intervaloTimer=null,booting=true;
function el(id){return document.getElementById(id)}
function setTexto(id,v){var i=el(id);if(i)i.textContent=v}
function setValor(id,v){var i=el(id);if(i)i.value=v}
function criarTimerVazio(){return{rodando:false,inicio:null,acumulado:0}}
function carregarJSON(k,f){try{var b=localStorage.getItem(k);return b?JSON.parse(b):f}catch(e){console.warn('Erro ao carregar '+k,e);return f}}
function salvarLocal(k,v){localStorage.setItem(k,JSON.stringify(v))}
function salvarJSON(k,v){salvarLocal(k,v);if(!booting)salvarOnline(k,v)}
function setStatusBanco(status){setTexto('statusBanco',status)}
function iniciarBancoOnline(){try{if(window.supabase){db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);dbOnline=true;setStatusBanco('Online')}else setStatusBanco('Local')}catch(e){console.warn('Supabase indisponível',e);setStatusBanco('Local')}}
async function salvarOnline(k,v){if(!dbOnline||!db)return;try{await db.from(SUPABASE_TABLE).upsert({key:k,value:v,updated_at:new Date().toISOString()},{onConflict:'key'});setStatusBanco('Online')}catch(e){console.warn('Erro ao salvar online',k,e);setStatusBanco('Local')}}
async function carregarEstadoOnline(){if(!dbOnline||!db)return;try{var keys=[STORAGE_REGISTROS,STORAGE_TIMER,STORAGE_META,STORAGE_CUSTOS];var resp=await db.from(SUPABASE_TABLE).select('key,value').in('key',keys);if(resp.error)throw resp.error;(resp.data||[]).forEach(function(row){salvarLocal(row.key,row.value);if(row.key===STORAGE_REGISTROS)registros=Array.isArray(row.value)?row.value:[];if(row.key===STORAGE_TIMER)timer=row.value||criarTimerVazio()});setStatusBanco('Online')}catch(e){console.warn('Erro ao carregar online',e);setStatusBanco('Local')}}
function converterNumeroBR(v){var s=String(v||'').trim();if(!s)return 0;s=s.replace(/[^0-9.,-]/g,'');if(s.indexOf(',')>=0){s=s.replace(/\./g,'').replace(',','.');return Number(s)||0}if(s.indexOf('.')>=0){var p=s.split('.'),milhar=p.length>1&&p.slice(1).every(function(x){return x.length===3});if(milhar)s=p.join('')}return Number(s)||0}
function numero(id){var i=el(id);return i?converterNumeroBR(i.value):0}
function formatarNumeroBR(v){return Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})}
function formatarMoedaCampo(e){var input=e.target,limpo=String(input.value||'').replace(/\D/g,''),n=(Number(limpo)/100).toFixed(2).replace('.',',');input.value=n.replace(/\B(?=(\d{3})+(?!\d))/g,'.')}
function formatarMilharCampo(e){var input=e.target,limpo=String(input.value||'').replace(/\D/g,'');input.value=limpo.replace(/\B(?=(\d{3})+(?!\d))/g,'.')}
function mostrarPagina(pagina){['controle','semana','mes','custos'].forEach(function(p){var id='pagina'+p.charAt(0).toUpperCase()+p.slice(1),btn='btnPagina'+p.charAt(0).toUpperCase()+p.slice(1),pg=el(id),b=el(btn);if(pg)pg.classList.toggle('active',p===pagina);if(b)b.classList.toggle('active',p===pagina)});if(pagina==='semana')buscarSemana();if(pagina==='mes')buscarMes()}
function salvarTimer(){salvarJSON(STORAGE_TIMER,timer)}
function tempoAtualMs(){if(!timer)return 0;if(!timer.rodando||!timer.inicio)return Number(timer.acumulado)||0;return(Number(timer.acumulado)||0)+(Date.now()-Number(timer.inicio))}
function converterMsParaHoras(ms){return Number(ms||0)/3600000}
function formatarTempo(ms){var t=Math.max(0,Math.floor(Number(ms||0)/1000)),h=Math.floor(t/3600),m=Math.floor((t%3600)/60),s=t%60;return[h,m,s].map(function(n){return String(n).padStart(2,'0')}).join(':')}
function formatarHorasHumanas(ms){return formatarTempo(ms)}
function converterHorasParaMs(valor){var texto=String(valor||'').trim();if(!texto)return 0;if(texto.indexOf(':')>=0){var partes=texto.split(':').map(function(p){return Number(p)||0}),h=partes[0]||0,m=partes[1]||0,s=partes[2]||0;return((h*3600)+(m*60)+s)*1000}return converterNumeroBR(texto)*3600000}
function formatarCampoHoras(){var campo=el('horas');if(!campo)return;campo.value=formatarTempo(converterHorasParaMs(campo.value));if(!timer.rodando){timer.acumulado=converterHorasParaMs(campo.value);timer.inicio=null;timer.modo='manual';salvarTimer()}}
function atualizarTimer(){var ms=tempoAtualMs();setTexto('timerDisplay',formatarTempo(ms));if(timer.rodando)setValor('horas',ms>0?formatarHorasHumanas(ms):'00:00:00');setTexto('timerStatus',timer.rodando?'Contando mesmo se fechar o site':(ms>0?'Temporizador pausado / horas editáveis':'Dia ainda não iniciado'))}
function ligarIntervaloTimer(){if(intervaloTimer)clearInterval(intervaloTimer);intervaloTimer=setInterval(function(){atualizarTimer();if(timer.rodando)salvarTimer()},1000)}
function iniciarTimer(){timer={rodando:true,inicio:Date.now(),acumulado:0,modo:'permanente'};salvarTimer();ligarIntervaloTimer();atualizarTimer()}
function pausarTimer(){if(!timer.rodando)return;timer.acumulado=tempoAtualMs();timer.rodando=false;timer.inicio=null;salvarTimer();atualizarTimer();setValor('horas',formatarTempo(timer.acumulado))}
function continuarTimer(){if(timer.rodando)return;timer.rodando=true;timer.inicio=Date.now();timer.modo='permanente';salvarTimer();ligarIntervaloTimer();atualizarTimer()}
function zerarTimer(){if(!confirm('Deseja zerar o temporizador do dia?'))return;timer=criarTimerVazio();salvarTimer();atualizarTimer();setValor('horas','00:00:00')}
function getCustosForm(){return{consumoKm:el('consumoKm')?el('consumoKm').value:'40',precoCombustivel:el('precoCombustivel')?el('precoCombustivel').value:'6,40',manutencaoValor:el('manutencaoValor')?el('manutencaoValor').value:'2.100,00',manutencaoKm:el('manutencaoKm')?el('manutencaoKm').value:'36.000',pneuValor:el('pneuValor')?el('pneuValor').value:'2.100,00',pneuKm:el('pneuKm')?el('pneuKm').value:'50.000',ipvaMensal:el('ipvaMensal')?el('ipvaMensal').value:'585,00',seguroMensal:el('seguroMensal')?el('seguroMensal').value:'600,00',financiamentoMensal:el('financiamentoMensal')?el('financiamentoMensal').value:'3.500,00',diasTrabalhadosMes:el('diasTrabalhadosMes')?el('diasTrabalhadosMes').value:'22'}}
function salvarCustosVeiculo(aviso){salvarJSON(STORAGE_CUSTOS,getCustosForm());calcularCustosAutomaticos();recalcularHistoricoCustos(false);atualizarTela();if(aviso)alert('Custos do veículo salvos e histórico recalculado.')}
function carregarCustosVeiculo(){var c=carregarJSON(STORAGE_CUSTOS,null);if(!c)return;Object.keys(c).forEach(function(k){setValor(k,c[k])})}
function calcularCustosPorKm(kmInformado){var km=Number(kmInformado||0),consumo=numero('consumoKm'),preco=numero('precoCombustivel'),manVal=numero('manutencaoValor'),manKm=numero('manutencaoKm'),pneuVal=numero('pneuValor'),pneuKm=numero('pneuKm'),ipva=numero('ipvaMensal'),seg=numero('seguroMensal'),fin=numero('financiamentoMensal'),diasTrab=numero('diasTrabalhadosMes')||22;var combust=consumo>0?(km/consumo)*preco:0,man=manKm>0?(manVal/manKm)*km:0,pneus=pneuKm>0?(pneuVal/pneuKm)*km:0,variavel=combust+man+pneus,fixo=diasTrab>0?(ipva+seg+fin)/diasTrab:0;return{variavelTotal:Number(variavel.toFixed(2)),fixoDiario:Number(fixo.toFixed(2)),combustivel:Number(variavel.toFixed(2)),custosAutomaticos:Number(fixo.toFixed(2))}}
function calcularCustosAutomaticos(){var c=calcularCustosPorKm(numero('km'));setValor('combustivel',formatarNumeroBR(c.variavelTotal));setValor('manutencao',formatarNumeroBR(c.fixoDiario))}
function recalcularHistoricoCustos(salvar){registros=registros.map(function(r){var c=calcularCustosPorKm(Number(r.km||0));return Object.assign({},r,{combustivel:c.combustivel,manutencao:c.custosAutomaticos})});if(salvar!==false)salvarJSON(STORAGE_REGISTROS,registros)}
function inicioDaSemana(txt){var d=txt?new Date(txt+'T00:00:00'):new Date(),dia=d.getDay(),diff=dia===0?-6:1-dia;d.setDate(d.getDate()+diff);d.setHours(0,0,0,0);return d}
function fimDaSemana(txt){var f=new Date(inicioDaSemana(txt));f.setDate(f.getDate()+6);f.setHours(23,59,59,999);return f}
function estaNaSemanaAtual(txt){if(!txt)return false;var d=new Date(txt+'T00:00:00');return d>=inicioDaSemana()&&d<=fimDaSemana()}
function diasRestantesSemana(){var hoje=new Date(),fim=fimDaSemana();hoje.setHours(0,0,0,0);fim.setHours(0,0,0,0);return Math.max(Math.floor((fim-hoje)/86400000)+1,0)}
function salvarMetaManual(){var meta=numero('metaSemanal');salvarJSON(STORAGE_META,meta);setTexto('metaInteligenteValor',BRL.format(meta));atualizarTela()}
function calcular(r){var fat=Number(r.uber||0)+Number(r.app99||0)+Number(r.outros||0),g=Number(r.combustivel||0)+Number(r.manutencao||0)+Number(r.extras||0),km=Number(r.km||0);return{faturamento:fat,gastos:g,lucro:fat-g,ganhosKm:km>0?fat/km:0}}
function montarRegistroAtual(){var km=numero('km'),c=calcularCustosPorKm(km),data=el('data')?el('data').value:'';setValor('combustivel',formatarNumeroBR(c.variavelTotal));setValor('manutencao',formatarNumeroBR(c.fixoDiario));var horasMs=timer.rodando?tempoAtualMs():converterHorasParaMs(el('horas')?el('horas').value:'00:00:00');return{id:data?Number(data.split('-').join('')):Date.now(),data:data,uber:numero('uber'),app99:numero('app99'),outros:numero('outros'),km:km,horas:Number(converterMsParaHoras(horasMs).toFixed(4)),combustivel:c.combustivel,manutencao:c.custosAutomaticos,extras:numero('extras')}}
function salvarRegistro(limparDepois){var r=montarRegistroAtual();if(!r.data){alert('Informe a data.');return false}var idx=registros.findIndex(function(i){return i.data===r.data});if(idx>=0){r.id=registros[idx].id;registros[idx]=r}else registros.push(r);salvarJSON(STORAGE_REGISTROS,registros);if(limparDepois)limparFormulario(false);atualizarTimer();atualizarTela();return true}
function fecharDia(){var ok=salvarRegistro(true);if(!ok)return;timer=criarTimerVazio();salvarTimer();atualizarTimer();setValor('horas','00:00:00');atualizarTela()}
function dataInput(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function preencherSemanaAtual(){setValor('semanaInicio',dataInput(inicioDaSemana()));setValor('semanaFim',dataInput(fimDaSemana()))}
function mesInput(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function preencherMesAtual(){setValor('mesBusca',mesInput(new Date()))}
function filtrarRegistrosPorMes(mesTexto){if(!mesTexto)return[];return registros.filter(function(r){return r.data&&r.data.slice(0,7)===mesTexto})}
function filtrarRegistrosPorPeriodo(i,f){if(!i||!f)return[];var ini=new Date(i+'T00:00:00'),fim=new Date(f+'T23:59:59');return registros.filter(function(r){if(!r.data)return false;var d=new Date(r.data+'T00:00:00');return d>=ini&&d<=fim})}
function buscarSemana(){var i=el('semanaInicio')?el('semanaInicio').value:'',f=el('semanaFim')?el('semanaFim').value:'';if(!i||!f){preencherSemanaAtual();i=el('semanaInicio').value;f=el('semanaFim').value}var lista=filtrarRegistrosPorPeriodo(i,f),bruto=0,gastos=0,lucro=0,km=0,horas=0;lista.forEach(function(r){var c=calcular(r);bruto+=c.faturamento;gastos+=c.gastos;lucro+=c.lucro;km+=Number(r.km||0);horas+=Number(r.horas||0)});setTexto('semanaMeta',BRL.format(numero('metaSemanal')));setTexto('semanaBruto',BRL.format(bruto));setTexto('semanaGastos',BRL.format(gastos));setTexto('semanaLucro',BRL.format(lucro));setTexto('semanaDias',String(lista.length));setTexto('semanaKm',km.toFixed(1)+' km');setTexto('semanaHoras',formatarHorasHumanas(horas*3600000));setTexto('semanaGanhoHora',BRL.format(horas>0?bruto/horas:0));setTexto('semanaGanhoKm',BRL.format(km>0?bruto/km:0));renderizarTabelaSemana(lista)}
function linhaSemana(r){var c=calcular(r),d=r.data?r.data.split('-').reverse().join('/'):'-';return '<td>'+d+'</td><td>'+BRL.format(r.uber||0)+'</td><td>'+BRL.format(r.app99||0)+'</td><td>'+BRL.format(c.faturamento)+'</td><td>'+BRL.format(c.gastos)+'</td><td><strong>'+BRL.format(c.lucro)+'</strong></td><td>'+Number(r.km||0).toFixed(1)+'</td><td>'+formatarHorasHumanas(Number(r.horas||0)*3600000)+'</td><td>'+BRL.format(c.ganhosKm)+'</td>'}
function buscarMes(){var mes=el('mesBusca')?el('mesBusca').value:'';if(!mes){preencherMesAtual();mes=el('mesBusca')?el('mesBusca').value:''}var lista=filtrarRegistrosPorMes(mes),bruto=0,gastos=0,lucro=0,km=0,horas=0;lista.forEach(function(r){var c=calcular(r);bruto+=c.faturamento;gastos+=c.gastos;lucro+=c.lucro;km+=Number(r.km||0);horas+=Number(r.horas||0)});var diasPlanejados=numero('diasTrabalhadosMes')||22,metaMensal=numero('metaSemanal')||0,faltaMeta=Math.max(metaMensal-bruto,0),progressoMeta=metaMensal>0?Math.min((bruto/metaMensal)*100,100):0,diasRestantes=Math.max(diasPlanejados-lista.length,0),precisaPorDia=diasRestantes>0?faltaMeta/diasRestantes:0;setValor('diasTrabalhadosMesResumo',String(diasPlanejados));setTexto('mesMeta',BRL.format(metaMensal));setTexto('mesFaltaMeta',BRL.format(faltaMeta));setTexto('mesProgressoMeta',progressoMeta.toFixed(1)+'%');setTexto('mesPrecisaPorDia',BRL.format(precisaPorDia));setTexto('mesBruto',BRL.format(bruto));setTexto('mesGastos',BRL.format(gastos));setTexto('mesLucro',BRL.format(lucro));setTexto('mesDias',String(lista.length));setTexto('mesKm',km.toFixed(1)+' km');setTexto('mesHoras',formatarHorasHumanas(horas*3600000));setTexto('mesGanhoHora',BRL.format(horas>0?bruto/horas:0));setTexto('mesGanhoKm',BRL.format(km>0?bruto/km:0));setTexto('mesMediaDia',BRL.format(lista.length>0?bruto/lista.length:0));renderizarTabelaMes(lista)}
function renderizarTabelaMes(lista){var t=el('tabelaMes');if(!t)return;t.innerHTML='';lista.slice().reverse().forEach(function(r){var c=calcular(r),d=r.data?r.data.split('-').reverse().join('/'):'-',tr=document.createElement('tr');tr.innerHTML='<td>'+d+'</td><td>'+BRL.format(r.uber||0)+'</td><td>'+BRL.format(r.app99||0)+'</td><td>'+BRL.format(c.faturamento)+'</td><td>'+BRL.format(c.gastos)+'</td><td><strong>'+BRL.format(c.lucro)+'</strong></td><td>'+Number(r.km||0).toFixed(1)+'</td><td>'+formatarHorasHumanas(Number(r.horas||0)*3600000)+'</td><td><button class="secondary" type="button" onclick="editarDia('+r.id+')">Editar</button></td>';t.appendChild(tr)})}
function renderizarTabelaSemana(lista){var t=el('tabelaSemana');if(!t)return;t.innerHTML='';lista.slice().reverse().forEach(function(r){var tr=document.createElement('tr');tr.innerHTML=linhaSemana(r);t.appendChild(tr)})}
function atualizarTela(){var hoje=dataInput(new Date()),hojeRegs=registros.filter(function(r){return r.data===hoje}),bruto=0,km=0,horas=0;hojeRegs.forEach(function(r){var c=calcular(r);bruto+=c.faturamento;km+=Number(r.km||0);horas+=Number(r.horas||0)});setTexto('valorTotalBrutoResumo',BRL.format(bruto));setTexto('lucroHora',BRL.format(horas>0?bruto/horas:0));setTexto('ganhoKmResumo',BRL.format(km>0?bruto/km:0));atualizarMetaSemanal();renderizarTabela();buscarSemana();buscarMes()}
function atualizarMetaSemanal(){var meta=numero('metaSemanal');salvarJSON(STORAGE_META,meta);var mesAtual=mesInput(new Date()),diasPlanejados=numero('diasTrabalhadosMes')||22,feito=0,dias=0;registros.filter(function(r){return r.data&&r.data.slice(0,7)===mesAtual}).forEach(function(r){feito+=calcular(r).faturamento;dias++});var falta=Math.max(meta-feito,0),prog=meta>0?Math.min((feito/meta)*100,100):0,restantes=Math.max(diasPlanejados-dias,0),precisa=restantes>0?falta/restantes:0,status='Abaixo';if(prog>=100)status='Meta batida';else if(prog>=70)status='No ritmo';setTexto('metaInteligenteValor',BRL.format(meta));setTexto('feitoSemana',BRL.format(feito));setTexto('faltaSemana',BRL.format(falta));setTexto('progressoSemana',prog.toFixed(1)+'%');setTexto('diasSemana',String(dias));setTexto('diasRestantesSemana',String(restantes));setTexto('precisaPorDiaSemana',BRL.format(precisa));setTexto('statusMetaSemana',status);var statusEl=el('statusMetaSemana');if(statusEl){statusEl.className=status==='Meta batida'?'value-positive':(status==='No ritmo'?'value-warning':'value-danger')}var b=el('barraMetaSemanal');if(b){b.style.width=prog+'%';b.style.background=prog>=100?'linear-gradient(90deg,#22c55e,#4ade80)':(prog>=70?'linear-gradient(90deg,#f59e0b,#fbbf24)':'linear-gradient(90deg,#2563eb,#38bdf8)')}}
function dinheiroInputTabela(id,campo,valor){return '<input class="table-input money-edit" id="edit_'+campo+'_'+id+'" type="text" value="'+formatarNumeroBR(valor||0)+'" inputmode="decimal">'}
function textoInputTabela(id,campo,valor,tipo){return '<input class="table-input" id="edit_'+campo+'_'+id+'" type="'+(tipo||'text')+'" value="'+String(valor||'')+'">'}
function renderizarTabela(){var t=el('tabela');if(!t)return;t.innerHTML='';registros.slice().reverse().forEach(function(r){var c=calcular(r),d=r.data?r.data.split('-').reverse().join('/'):'-',cls=c.lucro>=0?'ok':'bad',txt=c.lucro>=0?'Lucro':'Prejuízo',tr=document.createElement('tr');tr.id='linha_'+r.id;tr.innerHTML='<td>'+d+'</td><td>'+BRL.format(r.uber||0)+'</td><td>'+BRL.format(r.app99||0)+'</td><td>'+BRL.format(c.faturamento)+'</td><td>'+BRL.format(c.gastos)+'</td><td><strong>'+BRL.format(c.lucro)+'</strong></td><td>'+Number(r.km||0).toFixed(1)+'</td><td>'+formatarHorasHumanas(Number(r.horas||0)*3600000)+'</td><td>'+BRL.format(c.ganhosKm)+'</td><td><span class="pill '+cls+'">'+txt+'</span></td><td><button class="secondary" type="button" onclick="editarLinhaHistorico('+r.id+')">Editar</button> <button class="danger" type="button" onclick="excluir('+r.id+')">Excluir</button></td>';t.appendChild(tr)})}
function editarLinhaHistorico(id){var r=registros.find(function(item){return item.id===id});if(!r)return;var tr=el('linha_'+id);if(!tr)return;tr.classList.add('editing-row');tr.innerHTML='<td>'+textoInputTabela(id,'data',r.data||'', 'date')+'</td><td>'+dinheiroInputTabela(id,'uber',r.uber||0)+'</td><td>'+dinheiroInputTabela(id,'app99',r.app99||0)+'</td><td class="muted-cell">Auto</td><td class="muted-cell">Auto</td><td class="muted-cell">Auto</td><td>'+textoInputTabela(id,'km',Number(r.km||0).toString().replace('.',','),'text')+'</td><td>'+textoInputTabela(id,'horas',formatarTempo(Number(r.horas||0)*3600000),'text')+'</td><td class="muted-cell">Auto</td><td><span class="pill ok">Editando</span></td><td><button class="success" type="button" onclick="salvarLinhaHistorico('+id+')">Salvar</button> <button class="secondary" type="button" onclick="atualizarTela()">Cancelar</button></td>';Array.prototype.forEach.call(tr.querySelectorAll('.money-edit'),function(input){input.addEventListener('keyup',formatarMoedaCampo)})}
function salvarLinhaHistorico(id){var idx=registros.findIndex(function(item){return item.id===id});if(idx<0)return;var data=(el('edit_data_'+id)||{}).value||registros[idx].data;var km=converterNumeroBR((el('edit_km_'+id)||{}).value);var horasMs=converterHorasParaMs((el('edit_horas_'+id)||{}).value);var c=calcularCustosPorKm(km);registros[idx]=Object.assign({},registros[idx],{id:data?Number(data.split('-').join('')):id,data:data,uber:converterNumeroBR((el('edit_uber_'+id)||{}).value),app99:converterNumeroBR((el('edit_app99_'+id)||{}).value),km:km,horas:Number(converterMsParaHoras(horasMs).toFixed(4)),combustivel:c.combustivel,manutencao:c.custosAutomaticos});salvarJSON(STORAGE_REGISTROS,registros);atualizarTela()}
function editarDia(id){editarLinhaHistorico(id)}
function limparFormulario(manterData){var preservar=manterData!==false;['uber','app99','outros','km','combustivel','manutencao','extras'].forEach(function(id){setValor(id,'')});if(!timer.rodando)setValor('horas','00:00:00');calcularCustosAutomaticos();if(!preservar)definirDataHoje()}
function excluir(id){registros=registros.filter(function(r){return r.id!==id});salvarJSON(STORAGE_REGISTROS,registros);atualizarTela()}
function apagarTudo(){if(!confirm('Tem certeza que deseja apagar todos os registros?'))return;registros=[];localStorage.removeItem(STORAGE_REGISTROS);salvarJSON(STORAGE_REGISTROS,registros);atualizarTela()}
function exportarCSV(){var linhas=[['Data','Uber','99','Outros','Faturamento','Variavel','Fixos','Extras','Gastos','Lucro','KM','Horas','Ganhos por KM']];registros.forEach(function(r){var c=calcular(r);linhas.push([r.data,r.uber,r.app99,r.outros,c.faturamento,r.combustivel,r.manutencao,r.extras,c.gastos,c.lucro,r.km,r.horas,c.ganhosKm])});var csv=linhas.map(function(l){return l.join(';')}).join('\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8;'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='controle-uber-99.csv';link.click();URL.revokeObjectURL(url)}
function ativarMetaSemanal(){var c=el('metaSemanal');if(!c)return;c.value=formatarNumeroBR(carregarJSON(STORAGE_META,2500));c.addEventListener('keyup',formatarMoedaCampo);c.addEventListener('input',atualizarTela)}
function ativarCampoHoras(){var campo=el('horas');if(!campo)return;campo.addEventListener('blur',formatarCampoHoras);campo.addEventListener('change',formatarCampoHoras)}
function ativarCustosAutomaticos(){['km','consumoKm','precoCombustivel','diasTrabalhadosMes','manutencaoValor','manutencaoKm','pneuValor','pneuKm','ipvaMensal','seguroMensal','financiamentoMensal'].forEach(function(id){var c=el(id);if(c)c.addEventListener('input',function(){calcularCustosAutomaticos();salvarCustosVeiculo(false)})});['uber','app99','outros','extras','precoCombustivel','manutencaoValor','pneuValor','ipvaMensal','seguroMensal','financiamentoMensal'].forEach(function(id){var c=el(id);if(c)c.addEventListener('keyup',formatarMoedaCampo)});['diasTrabalhadosMes','manutencaoKm','pneuKm'].forEach(function(id){var c=el(id);if(c)c.addEventListener('keyup',formatarMilharCampo)});calcularCustosAutomaticos()}
function definirDataHoje(){var c=el('data');if(c)c.valueAsDate=new Date()}
function rodarTestes(){console.assert(typeof iniciarTimer==='function','Teste iniciarTimer definido falhou');console.assert(typeof pausarTimer==='function','Teste pausarTimer definido falhou');console.assert(converterNumeroBR('2.100,00')===2100,'Teste moeda brasileira falhou');console.assert(converterNumeroBR('214,46')===214.46,'Teste custo automático brasileiro falhou');console.assert(converterNumeroBR('36.000')===36000,'Teste milhar falhou');console.assert(formatarTempo(3661000)==='01:01:01','Teste formatar tempo falhou');console.assert(converterHorasParaMs('01:30:00')===5400000,'Teste converter horas manual falhou');var c=calcularCustosPorKm(150);console.assert(c.variavelTotal===39.05,'Teste custo variável 150km falhou');console.assert(c.fixoDiario===212.95,'Teste fixo diário falhou');console.assert(typeof editarDia==='function','Teste editar dia falhou');console.assert(typeof buscarMes==='function','Teste resumo mensal falhou')}
window.addEventListener('beforeunload',function(){salvarTimer()});document.addEventListener('visibilitychange',function(){salvarTimer();atualizarTimer()});
window.editarLinhaHistorico=editarLinhaHistorico;window.salvarLinhaHistorico=salvarLinhaHistorico;window.mostrarPagina=mostrarPagina;window.buscarSemana=buscarSemana;window.preencherSemanaAtual=preencherSemanaAtual;window.buscarMes=buscarMes;window.preencherMesAtual=preencherMesAtual;window.editarDia=editarDia;window.salvarMetaManual=salvarMetaManual;window.iniciarTimer=iniciarTimer;window.pausarTimer=pausarTimer;window.continuarTimer=continuarTimer;window.zerarTimer=zerarTimer;window.salvarRegistro=salvarRegistro;window.fecharDia=fecharDia;window.limparFormulario=limparFormulario;window.apagarTudo=apagarTudo;window.exportarCSV=exportarCSV;window.excluir=excluir;window.salvarCustosVeiculo=salvarCustosVeiculo;
document.addEventListener('DOMContentLoaded',async function(){booting=true;registros=carregarJSON(STORAGE_REGISTROS,[]);timer=carregarJSON(STORAGE_TIMER,criarTimerVazio());iniciarBancoOnline();await carregarEstadoOnline();definirDataHoje();carregarCustosVeiculo();ativarCustosAutomaticos();ativarCampoHoras();recalcularHistoricoCustos(false);ativarMetaSemanal();preencherSemanaAtual();preencherMesAtual();ligarIntervaloTimer();booting=false;atualizarTimer();if(!timer.rodando)setValor('horas',formatarTempo(tempoAtualMs()));atualizarTela();salvarJSON(STORAGE_REGISTROS,registros);rodarTestes()});
